; ESP32 Тээрэм — PlatformIO тохиргоо
; Board: ESP32-WROOM-32 (4MB flash)

[env:esp32-wroom]
platform = espressif32
board = esp32dev
framework = arduino

; ESP32-WROOM — 4MB flash
board_build.flash_size = 4MB
board_build.partitions = min_spiffs.csv
board_upload.flash_size = 4MB

monitor_speed = 115200

lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17

upload_speed = 921600
