; ============================================================
;  ESP32 Урсгал Хэмжигч — PlatformIO тохиргоо
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor хурд
monitor_speed = 115200

; Шаардлагатай сангууд
lib_deps =
    4-20ma/ModbusMaster@^2.0.1
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17

; Upload хурд
upload_speed = 921600
